from .user import UserMigration
from .seller import SellerMigration
from .card_type import CardTypeMigration
from .balance import BalanceMigration
from .deliveryZone import DeliveryZoneMigration
from .address import AddressMigration
from .category import CategoryMigration
from .product import ProductMigration
from .product_and_category import ProductAndCAtegoryMigration
from .promotion import PromotionMigration
from .delivery_tool_type import DeliveryToolTypeMigration
from .payment_method import PaymentMethodMigration
from .notification_type import NotificationTypeMigration