import random
from project.utils import create_slug
from ..models import Product
from .. import db

data_product = [
  {
      "name": "1 Spaghetti concentré",
      "image": "5.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Brochette de boeuf",
      "image": "6.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Riz à la sala",
      "image": "8.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails découpé",
      "image": "10.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Salade au poulet",
      "image": "11.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Hamburger dosé",
      "image": "13.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Pizza à la tomate",
      "image": "14.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Poulet à l\oeuf rond ",
      "image": "16.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Chocolat à cremé",
      "image": "17.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Spaghetti",
      "image": "19.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Shawarma",
      "image": "22.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Brochette de poulet",
      "image": "24.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Macaroni saucisse",
      "image": "25.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Riz avec crevettes",
      "image": "27.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Riz avec pomme frite",
      "image": "28.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "29.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Macaroni avec boule de poulet",
      "image": "30.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "7.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "9.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "12.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "15.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "18.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "20.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "21.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "23.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "26.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "1.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "31.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "3.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "36.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "32.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "38.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "33.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "37.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "36.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "34.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "29.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "35.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "39.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "48.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "47.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "49.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "46.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "50.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "45.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "43.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "41.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "44.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
      "name": "Trio de cocktails",
      "image": "42.jpg",
      "primary_price": 3000,
      "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
      "note": 4.5,
      "promotion_id": 1,
      "seller_id": 1,
  },
  {
    "name": "Trio de cocktails",
    "image": "40.jpg",
    "primary_price": 3000,
    "description": "Riz au gras aux saveurs de la viande de porc, idéal pour un déjeuner seul ou en famille. Chaque commande est accompagnée de boisson au choix (sucrerie ou bière) en plus d'un croissant. ",
    
    
    
    "note": 4.5,
    "promotion_id": 1,
      "seller_id": 1,
  },
  

]

class ProductMigration:
    @classmethod
    def migrate(cls):
        for item in data_product:
            slug = create_slug()
            product = Product(
                item.get("name"), 
                item.get("image"), 
                item.get("primary_price"), 
                "product-" + slug,
                item.get("description"), 
                random.choice([True, False]), 
                random.choice([True, False]), 
                item.get("note"), 
                item.get("promotion_id"), 
                item.get("seller_id"),
                )
            db.session.add(product)
            db.session.commit()
